// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data.EF;

namespace Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Comments", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<int>("replyId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            commentId = 1,
                            Comment = "Liver vô địch",
                            Count = 1,
                            postId = 1,
                            replyId = 0,
                            userId = 1
                        },
                        new
                        {
                            commentId = 2,
                            Comment = "Kèo căng",
                            Count = 0,
                            postId = 1,
                            replyId = 1,
                            userId = 3
                        });
                });

            modelBuilder.Entity("Server.Models.Friends", b =>
                {
                    b.Property<int>("friendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendId1")
                        .HasColumnType("int");

                    b.Property<int>("FriendId2")
                        .HasColumnType("int");

                    b.Property<bool>("IsFriend")
                        .HasColumnType("bit");

                    b.HasKey("friendId");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            friendId = 1,
                            FriendId1 = 1,
                            FriendId2 = 3,
                            IsFriend = false
                        },
                        new
                        {
                            friendId = 2,
                            FriendId1 = 4,
                            FriendId2 = 1,
                            IsFriend = true
                        },
                        new
                        {
                            friendId = 3,
                            FriendId1 = 4,
                            FriendId2 = 2,
                            IsFriend = true
                        });
                });

            modelBuilder.Entity("Server.Models.Messages", b =>
                {
                    b.Property<int>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("messageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            messageId = 1,
                            Message = "hello",
                            Name = "The Wall",
                            RoomId = 2
                        },
                        new
                        {
                            messageId = 2,
                            Message = "khoe chu",
                            Name = "Quang Linh",
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("Server.Models.Notifications", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Watch")
                        .HasColumnType("bit");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<int>("userId1")
                        .HasColumnType("int");

                    b.Property<int>("userId2")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            notificationId = 1,
                            Watch = false,
                            postId = 1,
                            userId1 = 1,
                            userId2 = 3
                        });
                });

            modelBuilder.Entity("Server.Models.Posts", b =>
                {
                    b.Property<int>("postId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("postId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            postId = 1,
                            Image = "cde",
                            Leter = "Trận chung kết",
                            Like = 0,
                            Title = "Champion League",
                            userId = 2
                        },
                        new
                        {
                            postId = 2,
                            Image = "ghi",
                            Leter = "Ta sẽ trở thành vua hải tặc",
                            Like = 0,
                            Title = "Laugh Tale",
                            userId = 3
                        },
                        new
                        {
                            postId = 3,
                            Image = "gkl",
                            Leter = "Dự án trang trại",
                            Like = 0,
                            Title = "Team châu phi",
                            userId = 4
                        });
                });

            modelBuilder.Entity("Server.Models.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Date = "09/05/2003",
                            Home = "Thanh Hóa",
                            Image = "https://yt3.ggpht.com/ytc/AKedOLQC7VSmgZqXr4zMng24lu62_yMTgF4XgK_3MbSW=s900-c-k-c0x00ffffff-no-rj",
                            Name = "The Wall",
                            Password = "TheWall123",
                            Relation = "Độc thân",
                            Username = "TheWall",
                            Word = "ĐH Công Nghiệp Hà Nội"
                        },
                        new
                        {
                            userId = 2,
                            Date = "26/12/2002",
                            Home = "Hà Nội",
                            Image = "https://www.inlogo.vn/vnt_upload/File/Image/51qwJMbFL2L_SX425__1.jpg",
                            Name = "Liverpool",
                            Password = "Liverpool123",
                            Relation = "Đang hẹn hò",
                            Username = "Liverpool",
                            Word = "ĐH Bách Khoa Hà Nội"
                        },
                        new
                        {
                            userId = 3,
                            Date = "22/07/2001",
                            Home = "Đà Nẵng",
                            Image = "https://symbols.vn/wp-content/uploads/2022/01/Hinh-One-Piece-Chibi-Cute-cuc-dang-yeu-cute.png",
                            Name = "One Piece",
                            Password = "OnePiece123",
                            Relation = "Đang hẹn hò",
                            Username = "OnePiece",
                            Word = "Tập Đoàn VinGroup"
                        },
                        new
                        {
                            userId = 4,
                            Date = "01/01/2000",
                            Home = "Nghệ An",
                            Image = "https://yt3.ggpht.com/ytc/AKedOLR9OE6wZfxH1MndE9YZOzpWHj92ifRwsMQgHTk2QA=s900-c-k-c0x00ffffff-no-rj",
                            Name = "Quang Linh",
                            Password = "QuangLinh123",
                            Relation = "Độc thân",
                            Username = "QuangLinh",
                            Word = "Angola"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
